// TODO: add permissions

module.exports = {
    ADMIN: 'ADMIN',
    MOD: 'MOD',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    LOGIN: 'LOGIN',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    UPDATE_PERMISSIONS: 'UPDATE_PERMISSIONS',

    // interest
    CREATE_INTEREST: 'CREATE_INTEREST',
    UPDATE_INTEREST: 'UPDATE_INTEREST',
    DELETE_INTEREST: 'DELETE_INTEREST',
}
